title: Μυρτώ Καλλιπολίτη
email: myname@gmail.com
# logo: 'island.jpg'
description: Αθήνα -- Wien -- Bruxelles
github_username: mkallipo
minimal_mistakes_skin: 'dirt'
search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


include:
  - _pages
  - assets

atom_feed:
  hide: true


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  #  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Myrto Kallipoliti"
  avatar : "twix.jpg"
  bio    : "Born and raised in Athens, lived in Vienna and currently reside in Brussels."
  location : Brussels - Athens
  links:
    - label: "Mytilene"
      icon: "<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M47.6 300.4L228.3 469.1c7.5 7 17.4 10.9 27.7 10.9s20.2-3.9 27.7-10.9L464.4 300.4c30.4-28.3 47.6-68 47.6-109.5v-5.8c0-69.9-50.5-129.5-119.4-141C347 36.5 300.6 51.4 268 84L256 96 244 84c-32.6-32.6-79-47.5-124.6-39.9C50.5 55.6 0 115.2 0 185.1v5.8c0 41.5 17.2 81.2 47.6 109.5z"/></svg>"
      url: "https://en.wikipedia.org/wiki/Mytilene"

    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mkallipo"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "http:www.linkedin.com/in/myrto-kallipoliti-212716146"
    - label: "Google Scholar"
      icon: "fab fa-fw fa-google"
      url: "https://scholar.google.com/citations?user=9zC1stoAAAAJ&hl=en"
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0000-0003-2188-6552"


defaults:
  # _posts
  - scope:
      path: "index.md"
      type: pages
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

#category_archive:
#  type: liquid
#  path: /categories/
#tag_archive:
#  type: liquid
#  path: /tags/
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-LVYFZN63KG"
    anonymize_ip: false # default
